version: "3"
services:
  postgres:
    build: docker/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASES: development,test
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./.env:/usr/src/app/.env
      - ./.env.development:/usr/src/app/.env.development
      - ./.env.test:/usr/src/app/.env.test
      - ./.sequelizerc:/usr/src/app/.sequelizerc
    ports:
      - 3000:3000
      - 3010:3010
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; nodemon dist/server.js'
    depends_on:
      - postgres
    stdin_open: true
    tty: true
